import Head from "next/head";
import AddAccount from "../components/add-account-form";
import Loader from "../components/loader";
import PrimaryButton from "../components/primary-button";
import { db } from "../config/firebase";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useAuth } from "../context/AuthContext";
import { useRouter } from "next/router";
import { collection, getDocs, addDoc } from "firebase/firestore";
import Link from "next/link";

export default function Home({ uid }) {
  const { user, logout } = useAuth();

  // const [users, setUsers] = useState<any[]>([]);
  const [accounts, setAccounts] = useState<any[]>([]);
  const usersCollectionRef = collection(db, "users");
  const userAccountsCollectionRef = collection(
    db,
    "users/" + user.uid + "/accounts"
  );
  const router = useRouter();

  // const getUsers = () => {
  //   getDocs(usersCollectionRef).then((data: any) => {
  //     setUsers(
  //       data.docs.map((doc: any) => {
  //         return { ...doc.data(), id: doc.id };
  //       })
  //     );
  //   });
  // };

  const getAccounts = () => {
    getDocs(userAccountsCollectionRef).then((data: any) => {
      setAccounts(
        data.docs.map((doc: any) => {
          return { ...doc.data(), id: doc.id };
        })
      );
    });
  };

  useEffect(() => {
    getAccounts();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Overview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="p-4">
          <AddAccount />
        </div>
        <div>
          {accounts &&
            accounts.map((account) => {
              return (
                <div key="account">
                  <h1 className="text-white">
                    {account.accountName}
                    <br />
                    {user.id}
                  </h1>
                </div>
              );
            })}
          <button
            className="bg-white p-4 flex items-center justify-center text-black"
            onClick={() => {
              logout();
              router.push("/login");
            }}
          >
            Logout
          </button>
        </div>
      </main>
    </>
  );
}
